/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Wolf390
 */
public class AppColorido extends javax.swing.JFrame {

    /**
     * Creates new form AppColorido
     */
    public AppColorido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpColorido = new javax.swing.JDesktopPane();
        mnbColorido = new javax.swing.JMenuBar();
        mnuPaletaCores = new javax.swing.JMenu();
        mniAzul = new javax.swing.JMenuItem();
        mniVermelho = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicativo Colorido 1.0");

        javax.swing.GroupLayout dtpColoridoLayout = new javax.swing.GroupLayout(dtpColorido);
        dtpColorido.setLayout(dtpColoridoLayout);
        dtpColoridoLayout.setHorizontalGroup(
            dtpColoridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        dtpColoridoLayout.setVerticalGroup(
            dtpColoridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        mnuPaletaCores.setText("Paleta");

        mniAzul.setText("Azul");
        mniAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAzulActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniAzul);

        mniVermelho.setText("Vermelho ");
        mniVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVermelhoActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniVermelho);
        mnuPaletaCores.add(jSeparator1);

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniSair);

        mnbColorido.add(mnuPaletaCores);

        mnuAjuda.setText("Ajuda");
        mnbColorido.add(mnuAjuda);

        setJMenuBar(mnbColorido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpColorido)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpColorido)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAzulActionPerformed
        // TODO add your handling code here:
        //Criação e Instância Objeto da Classe Conversor.
        Azul azul = new Azul();
        
        //Adicionar Objeto na Interface.
        dtpColorido.add(azul);
        
        //Exibindo o Objeto.
        azul.show();
    }//GEN-LAST:event_mniAzulActionPerformed

    private void mniVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVermelhoActionPerformed
        // TODO add your handling code here:
        //Criação e Instância Objeto da Classe Conversor.
        Vermelho vermelho = new Vermelho();
        
        //Adicionar Objeto na Interface.
        dtpColorido.add(vermelho);
        
        //Exibindo o Objeto.
        vermelho.show();
    }//GEN-LAST:event_mniVermelhoActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Ah! Vai não, vai!", "Sair!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_mniSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppColorido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpColorido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mnbColorido;
    private javax.swing.JMenuItem mniAzul;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVermelho;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuPaletaCores;
    // End of variables declaration//GEN-END:variables
}
